name: my_movie
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  flutter_bloc: ^8.1.3
  dartz: ^0.10.1
  equatable: ^2.0.5
  google_fonts: ^6.1.0
  flutter_rating_bar: ^4.0.1
  cached_network_image: ^3.3.0
  mocktail: ^1.0.1
  rxdart: ^0.27.7
  get_it: ^7.6.4
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  flutter_native_splash: ^2.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.2
  build_runner: ^2.4.6
  bloc_test: ^9.1.4

flutter_native_splash:
  color: "#000814"
  image: assets/logo.png

  android_12:
    image: assets/logo.png
    color: "#000814"

flutter:
  uses-material-design: true
  assets:
    - assets/